project:
  type: website

website:
  title: "Corban-FinalWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pdf/Resume-for-class.pdf
        text: Resume
      - href: pdf/Cover-letter.pdf
        text: Cover Letter
      - about.qmd

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true



