project:
  type: website

website:
  title: "Corban-FinalWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: FinalResult.qmd
        text: Olympic Projections
      - href: Hack-a-thon/HackFinal.qmd
        text: Hack-a-Thon
      - href: pdf/Resume-for-class.pdf
        text: Resume
      - href: pdf/Cover-letter.pdf
        text: Cover Letter
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true



